#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.fehbg &

xsetroot -cursor_name left_ptr &
bspc monitor HDMI-1 -d I II III IV V VI VII
bspc monitor eDP-1 -d VIII IX X

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# bspc query -M --names
# bspc monitor HDMI1 -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI1 -s HDMI2
